version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /
      - tools/memcached_benchmark
    schedule:
      interval: weekly
    cooldown: # applies only to non-security updates
      semver-patch-days: 3 # wait 3 days before applying patch updates
      semver-minor-days: 7
      semver-major-days: 14
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
