name: Update Nix Dependencies
on:
  workflow_dispatch:
  # push:
  #   branches: [ ci ] # for testing
  schedule:
    - cron: '0 0 * * 1' # Monday morning at 00:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-root-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update root flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "nix-flake: update root nix dependencies"
          pr-labels: |
            dependencies
            nix
          pr-body: |
            Automated update of root `flake.lock`.

  update-memcached-benchmark-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update tools/memcached_benchmark flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          path-to-flake-dir: tools/memcached_benchmark
          pr-title: "nix-flake: update memcached_benchmark nix dependencies"
          pr-labels: |
            dependencies
            nix
          pr-body: |
            Automated update of `tools/memcached_benchmark/flake.lock`.
